### ISSUE TITLE
Missing dependencies when running unit tests

### ISSUE THREAD

**Issue by jvillal-amp** [beaker-project/beaker-in-a-box#9]
I had to install the following RPMS in order to run the Server/run-tests.sh script in the develop branch.

```# yum install python2-mock python-pwquality python2-qpid-proton```

**Comment by jvillal-amp** [comment]
For LabController I had to also install:

```# yum install python-gssapi```

**Comment by StykMartin** [comment]
Running development on top of setup_beaker is not good decision. Instead of that you should use setup_sandbox. Sandbox will be fixed in PR #11
